AllCops:
  # TargetRubyVersion: 2.3
  Exclude:
    - 'db/*'
    - 'config/**/*'
    - 'bin/*'
Documentation:
  Enabled: false

MethodLength:
  Max: 20

ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 80

Metrics/ParameterLists:
  Max: 6

Metrics/AbcSize:
  Enabled: false
