# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61f6a01089a43bd3fd27166c3289b1271f0fab8cd21a382734fe6b68bef4ea0fe6af7e8b4db1834edb656cf19465f2e9356fdb7f650df0754e87fbb08750d9d0

test:
  secret_key_base: 80099c303171e211397be14e1bdf29bb9ed139a6baabf4e2da35f9d100baa3c1f64181b9aa19c191f2736f694f811191006726c1187884c2f86c7b6a28c67d64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
